user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

fos_user_security_login:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_registration_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting_reset:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile