back_office_homepage:
    path:     /
    defaults: { _controller: BackOfficeBundle:Home:homepage }

back_office_article_create:
    path:     /article/{origin}
    defaults: { _controller: BackOfficeBundle:Article:create}
    requirements:
        id: "[0-9]+"

back_office_article_activate:
    path:     /article/activate/{idArticle}
    defaults: { _controller: BackOfficeBundle:Article:activate}
    requirements:
        idArticle: "[0-9]+"

back_office_article_desactivate:
    path:     /article/desactivate/{idArticle}
    defaults: { _controller: BackOfficeBundle:Article:desactivate}
    requirements:
        idArticle: "[0-9]+"

back_office_article_delete:
    path:     /article/delete/{idArticle}
    defaults: { _controller: BackOfficeBundle:Article:delete}
    requirements:
        idArticle: "[0-9]+"





